# Generated by Django 3.0.5 on 2020-04-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='aliases',
        ),
    ]
